from web3 import Web3

# Connect to local Ethereum node (Ganache)
ganache_url = "http://127.0.0.1:7545"  # Default Ganache URL
web3 = Web3(Web3.HTTPProvider(ganache_url))

# Check connection
if not web3.is_Connected():
    print("Failed to connect to Ganache")
    exit()

# Replace with your contract's ABI and address
contract_address = "C:\Users\Md Naiyar Imam\decentralized-storage\smart_contracts"  # Replace with your contract's address
abi = []  # Replace with the ABI generated by Truffle

# Create contract instance
storage_contract = web3.eth.contract(address=contract_address, abi=abi)

# Create a new storage deal
def create_storage_deal(file_hash):
    account = web3.eth.accounts[0]  # Use the first account
    tx_hash = storage_contract.functions.createStorageDeal(file_hash).transact({'from': account})
    web3.eth.waitForTransactionReceipt(tx_hash)

# Example usage
create_storage_deal("example_file_hash")
